### ISSUE TITLE
![D7TR3%4YL}(3D)V2OC(8HDM_tmb](https://github.com/W1ndys/Easy-QFNU/assets/109416673/0b743e10-0a6a-4cb1-b672-66c8df6fc860)

### ISSUE THREAD

**Issue by GiantGKL** [W1ndys/Easy-QFNU#107]
![D7TR3%4YL}(3D)V2OC(8HDM_tmb](https://github.com/W1ndys/Easy-QFNU/assets/109416673/0b743e10-0a6a-4cb1-b672-66c8df6fc860)

_Originally posted by @W1ndys in https://github.com/W1ndys/Easy-QFNU/issues/88#issuecomment-2090010047_
            师哥你好厉害呀

**Comment by W1ndys** [comment]
@GiantGKL  大G哥你也好厉害呀，会写 [Lanqiao-Cup of Easy-QFNU](https://easy-qfnu.top/Cyber/Competition/Lanqiao-Cup/)
